### ISSUE TITLE
rename "manage" node class to something better

### ISSUE THREAD

**Issue by ketzacoatl** [ketzacoatl/compute-demo#15]
master is out, so is manage. ops? support? admin? ops-workers? non-compute?

**Comment by kerscher** [comment]
If there is only one cluster, why not `compute-demo`?

**Comment by ketzacoatl** [comment]
sorry, within the demo as a whole, there are 4 different roles. The roles are bastion, management, compute, and load-balancer. In nomad we map the role to "node classes", though nomad does not run on the bastion, so there are only 3 node classes. The "Management Tier" has the name "manage" in the asg, I am looking for a better word/phrase there. The purpose of the "Management Tier" is to run the ops tooling that is used/needed to run/manage/operate the deployment/env/cluster as a whole. So Prometheus, grafana, autoscaler, dns, logging tools, security tools, other stuff that is ops/admin in nature.

**Comment by kerscher** [comment]
`manage` does not strike me as bad at all. You could in theory use something like `system`, or `admin` I guess, but I don’t see a problem with the current one.

**Comment by ketzacoatl** [comment]
I think I would vote as `compute` and `ops` as a first choice, and maybe `compute` and `sys` as a second choice.

**Comment by kerscher** [comment]
After more thought and reading, it seems `system` or `sys` would be confusing, since system scheduled jobs run on all nodes. Between `ops` and `manage`, I actually prefer `manage`.

**Comment by ketzacoatl** [comment]
OK, I'll agree to leave it as-is for now.
