### ISSUE TITLE
include rkt in the demo

### ISSUE THREAD

**Issue by ketzacoatl** [ketzacoatl/compute-demo#5]
Add `rkt` capabilites. Needs at least:

- [X] `salstack` updates for installing `rkt` on nodes and on new AMI
- [X] Nomad client enabling `rkt` driver (if necessary)
- [ ] Nomad demo job for `rkt` task(s)
- [ ] Pipeline update for building both Docker and `rkt` images
- [ ] Running a pre-built Docker image with `rkt` and documenting differences
- [ ] Create storage for `rkt` images with security considerations baked-in

**Comment by ketzacoatl** [comment]
I have a basic salt formula to install the rkt tools (distributed as a .deb) - https://github.com/fpco/fpco-salt-formula/blob/data-ops-eval/rkt/install.sls.

**Comment by kerscher** [comment]
Closing due to addition of presentation with Docker secure setup and `rkt` (current) limitations with OCI.
